[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# list of libraries to link in the form of `<path to lib>:<lib name>:<address>`: `"src/MyLib.sol:MyLib:0x8De6DDbCd5053d32292AAA0D2105A32d108484a6"`
# the <path to lib> supports remappings
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
